### ISSUE TITLE
Changelog says latest release is 0.0.6

### ISSUE THREAD

**Issue by jayvdb** [moremoban/pypi-mobans#102]
https://github.com/moremoban/pypi-mobans/releases has only 0.0.3, which is out of date

If I can have committer access, I'll add the old tags

**Comment by chfw** [comment]
You should have it now.

**Comment by jayvdb** [comment]
Lovely.  Accurate tags are helpful because then https://github.com/github-changelog-generator/github-changelog-generator can be used to generate a changelog.md, which can be used to build our changelog.yml .  I used that process for the moban PR.

**Comment by jayvdb** [comment]
https://github.com/moremoban/pypi-mobans/commit/255752d472f5026669b1d5d6c3d4c64d618684f5 0.0.6

https://github.com/moremoban/pypi-mobans/commit/c1562e0092504c8060c07f8e4dbc00348d557fb7 0.0.5


Also https://github.com/moremoban/pypi-mobans/blob/dev/config/data.yml
uses `release: 0.0.0` and `version: 0.1.1rc3` - should update those also

**Comment by chfw** [comment]
assume it is corrected. a few month old now.
