### ISSUE TITLE
setup.py package exclude tests.*

### ISSUE THREAD

**Issue by jayvdb** [moremoban/pypi-mobans#128]
setuptools package exclude logic requires using `["tests", "tests.*"]`.

**Comment by chfw** [comment]
Yes. But Would it mean in opensuse testing, these tests will not run?

**Comment by jayvdb** [comment]
No, this is about what is installed during `setup.py install`, and currently all of your packages need a hack in the .spec to remove the installed tests directory.

The tests are run from out of the untarred sdist directory, and that is dependent on what is in `MANIFEST.in` - a separate enhancement that is also needed.

**Comment by chfw** [comment]
Oic
