### ISSUE TITLE
.travis.yml.jj2 broke all downstream projects' build

### ISSUE THREAD

**Issue by chfw** [moremoban/pypi-mobans#134]
see: https://github.com/moremoban/moban/issues/363

**Comment by chfw** [comment]
@ayan-b any chance for you to have a look?

**Comment by ayan-b** [comment]
@chfw Sure!

**Comment by ayan-b** [comment]
Looks like [Travis CI is going under maintenance](https://www.traviscistatus.com/), I will try to fix this tomorrow.
