### ISSUE TITLE
Mandatory CHANGELOG.rst

### ISSUE THREAD

**Issue by jayvdb** [moremoban/pypi-mobans#14]
This repo has a template for `CHANGELOG.rst`, but `setup.py.jj2` should be usable without a `CHANGELOG.rst`.

I have repos without any history-like file, and others using different filenames.  It is quite common for projects to use a variety of solutions for changelogs, and they may not want to have a redundant `CHANGELOG.rst` just to make use of this `setup.py.jj2` template.

I think the neatest easy solution is improve `setup.py` so that existence of `CHANGELOG.rst` is checked at runtime, and ignored if not present.

Then setup.py.jj2 can be more used now by people with other solutions for CHANGELOG, and more complicated or alternative solutions for CHANGELOG can then be added if people want to.

**Comment by jayvdb** [comment]
`templates/MANIFEST.in.jj2` also expects a `CHANGELOG.rst`

**Comment by chfw** [comment]
MANIFEST.in.jj2 is a bit hard to include a condition. let me invent something.

**Comment by jayvdb** [comment]
Ya, separate issue regarding `MANIFEST.in.jj2` : https://github.com/moremoban/pypi-mobans/issues/16

**Comment by chfw** [comment]
fixed by https://github.com/moremoban/pypi-mobans/commit/2c73a4222212723dbd26dc786f5edefbc9cead3b
