### ISSUE TITLE
setup.py.jj2 dropped a dependency

### ISSUE THREAD

**Issue by chfw** [moremoban/pypi-mobans#140]
The following dependency failed to show up in setup.py
`
-  - texttable>=0.8.2;python_version>="3"
`

causing released packages missed one dependency: https://travis-ci.org/github/pyexcel/pyexcel-io/jobs/682433323

**Comment by chfw** [comment]
@ayan-b  any idea? Looked at the code, I am not sure where `texttable` should have been mentioned.

**Comment by ayan-b** [comment]
@chfw Taking a look.

**Comment by ayan-b** [comment]
@chfw I am not able to reproduce the issue. :(
Getting `texttable>=0.8.2` in setup.py INSTALL_REQUIRES.

**Comment by ayan-b** [comment]
@chfw You have to add `setup_use_markers: true` in `pyexcel.yml` file as introduces by #92.

**Comment by chfw** [comment]
Please, could you write a note in pypi- Mobans readme?
