### ISSUE TITLE
Rename local.yml to mobanfile

### ISSUE THREAD

**Issue by jayvdb** [moremoban/pypi-mobans#25]
I see in moban repo there is a `mobanfile`.
Is that the preferred name for the file if `.moban.yml` is not able to be used?

The reason I didnt use `.moban.yml` is it breaks the tests due to https://github.com/moremoban/moban/issues/30

**Comment by chfw** [comment]
.moban.yml interferes moban's own unit test, hence I rename .moban.yml to mobanfile. 

The preferred name did not change and is still '.moban.yml'.

**Comment by chfw** [comment]
it is renamed to mobanfile
