### ISSUE TITLE
add CD pipeline through travis-ci

### ISSUE THREAD

**Issue by chfw** [moremoban/pypi-mobans#44]
there is a possibility that travis-ci does the `python setup.py publish` for the developer. hence, it is a good productivity improvement. 

to release, developer just needs to provide release tag.

**Comment by jayvdb** [comment]
https://docs.travis-ci.com/user/using-workspaces/ can help collect multiple versions and do a final check everything is ok before doing a publish

**Comment by chfw** [comment]
it is now done via github actions
