### ISSUE TITLE
Pipfile template did not include dev-packages section

### ISSUE THREAD

**Issue by chfw** [moremoban/pypi-mobans#58]
https://github.com/moremoban/pypi-mobans/pull/48

According to: https://pipenv.readthedocs.io/en/latest/basics/#example-pipfile-pipfile-lock, there is a dev-packages section. I think tests/requirements.txt shall go there too.

@siddhpant, would you like to take one step further?

**Comment by chfw** [comment]
Here is an example output from pyexcel-xlsx:

here is the tests/requirements.txt: https://github.com/pyexcel/pyexcel-xlsx/blob/master/.moban.d/tests/requirements.txt
```
[[source]]
url = 'https://pypi.python.org/simple'
verify_ssl = true
name = 'pypi'

[requires]
python_version= '3.6'

[packages]
    openpyxl>=2.4.4
    pyexcel-io>=0.5.3
```

**Comment by siddhpant** [comment]
@chfw Should I add reading lines from the file? Or the old block method is fine?

**Comment by chfw** [comment]
I think what you have is great. It does what pypi-mobans' tests/requirements.jj2 does. 

You are also welcome to challenge the status quo. For example, dependencies are specified in yaml file as a list whereas the dev dependencies are specified as a block of text and downstream project to extend them. For consistency, it is better that both are done in the same manner. And a list in yaml file is preferred because it can be programmatically read. So are you interested in finding a solution to use a list of project yaml file and populate the pipfile, and at the same time, allow downstream project to append what they need?

I am happy on what you have done so far. If you stop where you are at the moment, it is fine too. So it is up to you.
