### ISSUE TITLE
Pipfile template for pipenv support

### ISSUE THREAD

**Issue by jayvdb** [moremoban/pypi-mobans#6]
https://github.com/pypa/pipenv is all the rage now.  We should have a template for generating it.

**Comment by siddhpant** [comment]
Which should be the version for Python? 2 or 3?

**Comment by chfw** [comment]
Ideally both versions. Python 2.7 will end by 2020, 14 months to go.

**Comment by siddhpant** [comment]
I know, but pipenv doesn't support two versions simultaneously.

https://github.com/pypa/pipenv/issues/1050

**Comment by jayvdb** [comment]
Please do this discussion on Zulip, not here in GitHub.
