### ISSUE TITLE
Python version classifiers

### ISSUE THREAD

**Issue by jayvdb** [moremoban/pypi-mobans#7]
All versions 2.6,2.7,3.3+ are in the classifiers.

https://github.com/moremoban/pypi-mobans/blob/master/templates/setup.py.jj2#L64

That is extremely rare these days, with lots of tools breaking on py26 and py33, and many packages moving to py3 only, or even py34/py35 only in order to use the new syntax they provide which is not backwards compatible.

A simple approach is to provide a 'minimum python version' defaulting to 2.6, and then (possibly a latter enhancement) add a more complicated 'unsupported python versions' which defaults to 3.0-3.2

**Comment by jayvdb** [comment]
Also classifier `Programming Language :: Python :: 3 :: Only` can be added if the lowest version is 3 or higher.

**Comment by chfw** [comment]
This feels like the version classifier should be left for the user to decide. Once hardcoded, it is not going away.

**Comment by jayvdb** [comment]
But a minimum version is still needed.

There is lots of py26 & py27 related code in the setup.py.jj2 template, which could be omitted if the minimum version was known.

**Comment by jayvdb** [comment]
Adding a license range will allow using `python_requires` to setup template , and/or `python-tag` in setup.cfg to ensure the wheel doesnt install on incorrect versions.
