### ISSUE TITLE
Keywords missing trailing commas

### ISSUE THREAD

**Issue by jayvdb** [moremoban/pypi-mobans#8]
See https://github.com/pyexcel/pyexcel/blob/8a94f9f/setup.py#L30 which has

```py
KEYWORDS = [
    'tsv',
    'tsvz'
    'csv',
    'csvz',
    'xls',
    'xlsx',
    'ods'
    'python'
]
```

**Comment by jayvdb** [comment]
The easy solution for this problem is to move

```jinja2
    {%block additional_keywords%}
    {%endblock%}
```

to the last position of the `KEYWORDS` creation.  Then it does not matter if the block `additional_keywords` did not include a trailing comma.

**Comment by jayvdb** [comment]
Another solution is to save the block as a variable and inspect it; something like
```jinja2
{% set keywords = self.keywords() %}
{% if not keywords.endswith(',') %}
{% set keywords = keywords + ',' %}
{% endif %}
```

**Comment by chfw** [comment]
safer, isn't it?
